const elements = [
  {
    element: 'Hydrogen',
    abbreviation: 'H',
    type: 'Nonmetal',
    state: 'Gas',
    atomicNumber: '1',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Helium',
    abbreviation: 'He',
    type: 'Noble Gas',
    state: 'Gas',
    atomicNumber: '2',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Lithium',
    abbreviation: 'Li',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: '3',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Beryllium',
    abbreviation: 'Be',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: '4',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Boron',
    abbreviation: 'B',
    type: 'Metalloid',
    state: '',
    atomicNumber: '5',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Carbon',
    abbreviation: 'C',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '6',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Nitrogen',
    abbreviation: 'N',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '7',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Oxygen',
    abbreviation: 'O',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '8',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Fluorine',
    abbreviation: 'F',
    type: 'Halogen',
    state: '',
    atomicNumber: '9',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Neon',
    abbreviation: 'Ne',
    type: 'Noble Gas',
    state: 'Gas',
    atomicNumber: '10',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Sodium',
    abbreviation: 'Na',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: '11',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Magnesium',
    abbreviation: 'Mg',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: '12',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Aluminum',
    abbreviation: 'Al',
    type: 'Basic Metal',
    state: 'Solid',
    atomicNumber: '13',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Silicon',
    abbreviation: 'Si',
    type: 'Metalloid',
    state: '',
    atomicNumber: '14',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Phosphorus',
    abbreviation: 'P',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '15',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Sulfur',
    abbreviation: 'S',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '16',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Chlorine',
    abbreviation: 'Cl',
    type: 'Halogen',
    state: '',
    atomicNumber: '17',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Argon',
    abbreviation: 'Ar',
    type: 'Noble Gas',
    state: '',
    atomicNumber: '18',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Potassium',
    abbreviation: 'K',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: '19',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Calcium',
    abbreviation: 'Ca',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: '20',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Scandium',
    abbreviation: 'Sc',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '21',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Titanium',
    abbreviation: 'Ti',
    type: 'Transition Metal',
    state: 'Solid',
    atomicNumber: '22',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Vanadium',
    abbreviation: 'V',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '23',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Chromium',
    abbreviation: 'Cr',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '24',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Manganese',
    abbreviation: 'Mn',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '25',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Iron',
    abbreviation: 'Fe',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '26',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Cobalt',
    abbreviation: 'Co',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '27',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Nickel',
    abbreviation: 'Ni',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '28',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Copper',
    abbreviation: 'Cu',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '29',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Zinc',
    abbreviation: 'Zn',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '30',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: '',
    abbreviation: '',
    type: '',
    state: '',
    atomicNumber: '',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
]