let elementsArray = [
  {
    element: 'Hydrogen',
    abbreviation: 'H',
    type: 'Nonmetal',
    state: 'Gas',
    atomicNumber: '1',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Helium',
    abbreviation: 'He',
    type: 'Noble Gas',
    state: 'Gas',
    atomicNumber: '2',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Lithium',
    abbreviation: 'Li',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: '3',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Beryllium',
    abbreviation: 'Be',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: '4',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Boron',
    abbreviation: 'B',
    type: 'Metalloid',
    state: '',
    atomicNumber: '5',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Carbon',
    abbreviation: 'C',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '6',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Nitrogen',
    abbreviation: 'N',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '7',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Oxygen',
    abbreviation: 'O',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '8',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Fluorine',
    abbreviation: 'F',
    type: 'Halogen',
    state: '',
    atomicNumber: '9',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Neon',
    abbreviation: 'Ne',
    type: 'Noble Gas',
    state: 'Gas',
    atomicNumber: '10',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Sodium',
    abbreviation: 'Na',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: '11',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Magnesium',
    abbreviation: 'Mg',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: '12',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Aluminum',
    abbreviation: 'Al',
    type: 'Basic Metal',
    state: 'Solid',
    atomicNumber: '13',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Silicon',
    abbreviation: 'Si',
    type: 'Metalloid',
    state: '',
    atomicNumber: '14',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Phosphorus',
    abbreviation: 'P',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '15',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Sulfur',
    abbreviation: 'S',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '16',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Chlorine',
    abbreviation: 'Cl',
    type: 'Halogen',
    state: '',
    atomicNumber: '17',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Argon',
    abbreviation: 'Ar',
    type: 'Noble Gas',
    state: '',
    atomicNumber: '18',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Potassium',
    abbreviation: 'K',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: '19',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Calcium',
    abbreviation: 'Ca',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: '20',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Scandium',
    abbreviation: 'Sc',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '21',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Titanium',
    abbreviation: 'Ti',
    type: 'Transition Metal',
    state: 'Solid',
    atomicNumber: '22',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Vanadium',
    abbreviation: 'V',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '23',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Chromium',
    abbreviation: 'Cr',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '24',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Manganese',
    abbreviation: 'Mn',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '25',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Iron',
    abbreviation: 'Fe',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '26',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Cobalt',
    abbreviation: 'Co',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '27',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Nickel',
    abbreviation: 'Ni',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '28',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Copper',
    abbreviation: 'Cu',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '29',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Zinc',
    abbreviation: 'Zn',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '30',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Gallium',
    abbreviation: 'Ga',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '31',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Germanium',
    abbreviation: 'Ge',
    type: 'Metalloid',
    state: '',
    atomicNumber: '32',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Arsenic',
    abbreviation: 'As',
    type: 'Metalloid',
    state: '',
    atomicNumber: '33',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Selenium',
    abbreviation: 'Se',
    type: 'Nonmetal',
    state: '',
    atomicNumber: '34',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Bromine',
    abbreviation: 'Br',
    type: 'Halogen',
    state: '',
    atomicNumber: '35',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Krypton',
    abbreviation: 'Kr',
    type: 'Noble Gas',
    state: '',
    atomicNumber: '36',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Rubidium',
    abbreviation: 'Rb',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: '37',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Strontium',
    abbreviation: 'Sr',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: '38',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Yttrium',
    abbreviation: 'Y',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '39',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Zirconium',
    abbreviation: 'Zr',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '40',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Niobium',
    abbreviation: 'Nb',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '41',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Molybdenum',
    abbreviation: 'Mo',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '42',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Technetium',
    abbreviation: 'Tc',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '43',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Ruthenium',
    abbreviation: 'Ru',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '44',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Rhodium',
    abbreviation: 'Rh',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '45',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Palladium',
    abbreviation: 'Pd',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '46',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Silver',
    abbreviation: 'Ag',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '47',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Cadmium',
    abbreviation: 'Cd',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '48',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Indium',
    abbreviation: 'In',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '49',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Tin',
    abbreviation: 'S',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '50',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Antimony',
    abbreviation: 'Sb',
    type: 'Metalloid',
    state: '',
    atomicNumber: '51',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Tellurium',
    abbreviation: 'Te',
    type: 'Metalloid',
    state: '',
    atomicNumber: '52',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Iodine',
    abbreviation: 'I',
    type: 'Halogen',
    state: '',
    atomicNumber: '53',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Xenon',
    abbreviation: 'Xe',
    type: 'Noble Gas',
    state: '',
    atomicNumber: '54',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Cesium',
    abbreviation: 'Cs',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: '55',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Barium',
    abbreviation: 'Ba',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: '56',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Hafnium',
    abbreviation: 'Hf',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '72',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Tantalum',
    abbreviation: 'Ta',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '73',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Tungsten',
    abbreviation: 'W',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 'W',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Rhenium',
    abbreviation: 'Re',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '75',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Osmium',
    abbreviation: 'Os',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '76',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Iridium',
    abbreviation: 'Ir',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '77',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Platinum',
    abbreviation: 'Pt',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '78',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Gold',
    abbreviation: 'Au',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '79',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Mercury',
    abbreviation: 'Hg',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '80',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Thallium',
    abbreviation: 'Tl',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '81',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Lead',
    abbreviation: 'Pb',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '82',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Bismuth',
    abbreviation: 'Bi',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '83',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Polonium',
    abbreviation: 'Po',
    type: 'Metalloid',
    state: '',
    atomicNumber: '84',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Astatine',
    abbreviation: 'At',
    type: 'Halogen',
    state: '',
    atomicNumber: '85',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Radon',
    abbreviation: 'Rn',
    type: 'Noble Gas',
    state: '',
    atomicNumber: '86',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Francium',
    abbreviation: 'Fr',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: '87',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Radium',
    abbreviation: 'Ra',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: '88',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Rutherfordium',
    abbreviation: 'Rf',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '104',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Dubinium',
    abbreviation: 'Db',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '105',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Seaborgium',
    abbreviation: 'Sg',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '106',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Bohrium',
    abbreviation: 'Bh',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '107',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Hassium',
    abbreviation: 'Hs',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '108',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Meitnerium',
    abbreviation: 'Mt',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '109',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Darmstadtium',
    abbreviation: 'Ds',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '110',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Roentgenium',
    abbreviation: 'Rg',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '111',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Copernicium',
    abbreviation: 'Cn',
    type: 'Transition Metal',
    state: '',
    atomicNumber: '112',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Ununtrium',
    abbreviation: 'Uut',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '113',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Flerovium',
    abbreviation: 'Fl',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '114',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Ununpentium',
    abbreviation: 'Uup',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '115',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Livermorium',
    abbreviation: 'Lv',
    type: 'Basic Metal',
    state: '',
    atomicNumber: '116',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Ununseptium',
    abbreviation: 'Uus',
    type: 'Halogen',
    state: '',
    atomicNumber: '117',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Ununoctium',
    abbreviation: 'Uuo',
    type: 'Noble Gas',
    state: '',
    atomicNumber: '118',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Lanthenum',
    abbreviation: 'La',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '57',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Cerium',
    abbreviation: 'Ce',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '58',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Praseodymium',
    abbreviation: 'Pr',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '59',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Neodymium',
    abbreviation: 'Nd',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '60',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Promethium',
    abbreviation: 'Pm',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '61',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Samarium',
    abbreviation: 'Sm',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '62',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Europium',
    abbreviation: 'Eu',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '63',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Gadolinium',
    abbreviation: 'Gd',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '64',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Terbium',
    abbreviation: 'Tb',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '65',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Dysprosium',
    abbreviation: 'Dy',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '66',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Holmium',
    abbreviation: 'Ho',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '67',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Erbium',
    abbreviation: 'Er',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '68',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Thullum',
    abbreviation: 'Tm',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '69',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Ytterbium',
    abbreviation: 'Yb',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '70',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Lutetium',
    abbreviation: 'Lu',
    type: 'Lanthanide',
    state: '',
    atomicNumber: '71',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Actinium',
    abbreviation: 'Ac',
    type: 'Actinide',
    state: '',
    atomicNumber: '89',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Thorium',
    abbreviation: 'Th',
    type: 'Actinide',
    state: '',
    atomicNumber: '90',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Protactinium',
    abbreviation: 'Pa',
    type: '',
    state: '',
    atomicNumber: '91',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Uranium',
    abbreviation: 'U',
    type: 'Actinide',
    state: '',
    atomicNumber: '92',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Neptunium',
    abbreviation: 'Np',
    type: 'Actinide',
    state: '',
    atomicNumber: '93',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Plutonium',
    abbreviation: 'Pu',
    type: 'Actinide',
    state: '',
    atomicNumber: '94',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Americium',
    abbreviation: 'Am',
    type: 'Actinide',
    state: '',
    atomicNumber: '95',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Curium',
    abbreviation: 'Cm',
    type: 'Actinide',
    state: '',
    atomicNumber: '96',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Berkelium',
    abbreviation: 'Bk',
    type: 'Actinide',
    state: '',
    atomicNumber: '97',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Californium',
    abbreviation: 'Cf',
    type: 'Actinide',
    state: '',
    atomicNumber: '98',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Einsteinium',
    abbreviation: 'Es',
    type: 'Actinide',
    state: '',
    atomicNumber: '99',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Fermium',
    abbreviation: 'Fm',
    type: 'Actinide',
    state: '',
    atomicNumber: '100',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Mendelevium',
    abbreviation: 'Md',
    type: 'Actinide',
    state: '',
    atomicNumber: '101',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Nobelium',
    abbreviation: 'No',
    type: 'Actinide',
    state: '',
    atomicNumber: '102',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
  {
    element: 'Lawrencium',
    abbreviation: 'Lr',
    type: 'Actinide',
    state: '',
    atomicNumber: '103',
    atomicWeight: '',
    protons: '',
    neutrons: '',
    electrons: ''
  },
]

const elements = document.getElementById('elements');
console.log(elements);
function renderElements () {
	elements.innerHTML = '';

	elementsArray.forEach((element) => {
  	const listElement = document.createElement('li');

    const text = document.createElement('span');
    text.textContent = element.element;
    text.className = 'element';
    listElement.appendChild(text);

    elements.appendChild(listElement);
  });
}

renderElements();