let elementsArray = [
  {
    element: 'Hydrogen',
    abbreviation: 'H',
    type: 'Nonmetal',
    state: 'Gas',
    atomicNumber: 1,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Helium',
    abbreviation: 'He',
    type: 'Noble Gas',
    state: 'Gas',
    atomicNumber: 2,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Lithium',
    abbreviation: 'Li',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: 3,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Beryllium',
    abbreviation: 'Be',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: 4,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Boron',
    abbreviation: 'B',
    type: 'Metalloid',
    state: '',
    atomicNumber: 5,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Carbon',
    abbreviation: 'C',
    type: 'Nonmetal',
    state: '',
    atomicNumber: 6,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Nitrogen',
    abbreviation: 'N',
    type: 'Nonmetal',
    state: '',
    atomicNumber: 7,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Oxygen',
    abbreviation: 'O',
    type: 'Nonmetal',
    state: '',
    atomicNumber: 8,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Fluorine',
    abbreviation: 'F',
    type: 'Halogen',
    state: '',
    atomicNumber: 9,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Neon',
    abbreviation: 'Ne',
    type: 'Noble Gas',
    state: 'Gas',
    atomicNumber: 10,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Sodium',
    abbreviation: 'Na',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: 11,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Magnesium',
    abbreviation: 'Mg',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: 12,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Aluminum',
    abbreviation: 'Al',
    type: 'Basic Metal',
    state: 'Solid',
    atomicNumber: 13,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Silicon',
    abbreviation: 'Si',
    type: 'Metalloid',
    state: '',
    atomicNumber: 14,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Phosphorus',
    abbreviation: 'P',
    type: 'Nonmetal',
    state: '',
    atomicNumber: 15,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Sulfur',
    abbreviation: 'S',
    type: 'Nonmetal',
    state: '',
    atomicNumber: 16,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Chlorine',
    abbreviation: 'Cl',
    type: 'Halogen',
    state: '',
    atomicNumber: 17,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Argon',
    abbreviation: 'Ar',
    type: 'Noble Gas',
    state: '',
    atomicNumber: 18,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Potassium',
    abbreviation: 'K',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: 19,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Calcium',
    abbreviation: 'Ca',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: 20,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Scandium',
    abbreviation: 'Sc',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 21,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Titanium',
    abbreviation: 'Ti',
    type: 'Transition Metal',
    state: 'Solid',
    atomicNumber: 22,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Vanadium',
    abbreviation: 'V',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 23,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Chromium',
    abbreviation: 'Cr',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 24,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Manganese',
    abbreviation: 'Mn',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 25,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Iron',
    abbreviation: 'Fe',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 26,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Cobalt',
    abbreviation: 'Co',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 27,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Nickel',
    abbreviation: 'Ni',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 28,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Copper',
    abbreviation: 'Cu',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 29,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Zinc',
    abbreviation: 'Zn',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 30,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Gallium',
    abbreviation: 'Ga',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 31,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Germanium',
    abbreviation: 'Ge',
    type: 'Metalloid',
    state: '',
    atomicNumber: 32,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Arsenic',
    abbreviation: 'As',
    type: 'Metalloid',
    state: '',
    atomicNumber: 33,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Selenium',
    abbreviation: 'Se',
    type: 'Nonmetal',
    state: '',
    atomicNumber: 34,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Bromine',
    abbreviation: 'Br',
    type: 'Halogen',
    state: '',
    atomicNumber: 35,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Krypton',
    abbreviation: 'Kr',
    type: 'Noble Gas',
    state: '',
    atomicNumber: 36,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Rubidium',
    abbreviation: 'Rb',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: 37,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Strontium',
    abbreviation: 'Sr',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: 38,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Yttrium',
    abbreviation: 'Y',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 39,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Zirconium',
    abbreviation: 'Zr',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 40,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Niobium',
    abbreviation: 'Nb',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 41,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Molybdenum',
    abbreviation: 'Mo',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 42,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Technetium',
    abbreviation: 'Tc',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 43,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Ruthenium',
    abbreviation: 'Ru',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 44,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Rhodium',
    abbreviation: 'Rh',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 45,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Palladium',
    abbreviation: 'Pd',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 46,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Silver',
    abbreviation: 'Ag',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 47,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Cadmium',
    abbreviation: 'Cd',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 48,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Indium',
    abbreviation: 'In',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 49,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Tin',
    abbreviation: 'S',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 50,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Antimony',
    abbreviation: 'Sb',
    type: 'Metalloid',
    state: '',
    atomicNumber: 51,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Tellurium',
    abbreviation: 'Te',
    type: 'Metalloid',
    state: '',
    atomicNumber: 52,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Iodine',
    abbreviation: 'I',
    type: 'Halogen',
    state: '',
    atomicNumber: 53,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Xenon',
    abbreviation: 'Xe',
    type: 'Noble Gas',
    state: '',
    atomicNumber: 54,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Cesium',
    abbreviation: 'Cs',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: 55,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Barium',
    abbreviation: 'Ba',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: 56,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Hafnium',
    abbreviation: 'Hf',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 72,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Tantalum',
    abbreviation: 'Ta',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 73,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Tungsten',
    abbreviation: 'W',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 74,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Rhenium',
    abbreviation: 'Re',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 75,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Osmium',
    abbreviation: 'Os',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 76,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Iridium',
    abbreviation: 'Ir',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 77,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Platinum',
    abbreviation: 'Pt',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 78,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Gold',
    abbreviation: 'Au',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 79,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Mercury',
    abbreviation: 'Hg',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 80,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Thallium',
    abbreviation: 'Tl',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 81,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Lead',
    abbreviation: 'Pb',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 82,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Bismuth',
    abbreviation: 'Bi',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 83,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Polonium',
    abbreviation: 'Po',
    type: 'Metalloid',
    state: '',
    atomicNumber: 84,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Astatine',
    abbreviation: 'At',
    type: 'Halogen',
    state: '',
    atomicNumber: 85,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Radon',
    abbreviation: 'Rn',
    type: 'Noble Gas',
    state: '',
    atomicNumber: 86,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Francium',
    abbreviation: 'Fr',
    type: 'Alkali Metal',
    state: '',
    atomicNumber: 87,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Radium',
    abbreviation: 'Ra',
    type: 'Alkaline Earth',
    state: '',
    atomicNumber: 88,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Rutherfordium',
    abbreviation: 'Rf',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 104,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Dubinium',
    abbreviation: 'Db',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 105,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Seaborgium',
    abbreviation: 'Sg',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 106,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Bohrium',
    abbreviation: 'Bh',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 107,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Hassium',
    abbreviation: 'Hs',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 108,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Meitnerium',
    abbreviation: 'Mt',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 109,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Darmstadtium',
    abbreviation: 'Ds',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 110,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Roentgenium',
    abbreviation: 'Rg',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 111,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Copernicium',
    abbreviation: 'Cn',
    type: 'Transition Metal',
    state: '',
    atomicNumber: 112,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Ununtrium',
    abbreviation: 'Uut',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 113,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Flerovium',
    abbreviation: 'Fl',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 114,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Ununpentium',
    abbreviation: 'Uup',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 115,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Livermorium',
    abbreviation: 'Lv',
    type: 'Basic Metal',
    state: '',
    atomicNumber: 116,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Ununseptium',
    abbreviation: 'Uus',
    type: 'Halogen',
    state: '',
    atomicNumber: 117,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Ununoctium',
    abbreviation: 'Uuo',
    type: 'Noble Gas',
    state: '',
    atomicNumber: 118,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Lanthenum',
    abbreviation: 'La',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 57,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Cerium',
    abbreviation: 'Ce',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 58,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Praseodymium',
    abbreviation: 'Pr',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 59,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Neodymium',
    abbreviation: 'Nd',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 60,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Promethium',
    abbreviation: 'Pm',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 61,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Samarium',
    abbreviation: 'Sm',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 62,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Europium',
    abbreviation: 'Eu',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 63,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Gadolinium',
    abbreviation: 'Gd',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 64,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Terbium',
    abbreviation: 'Tb',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 65,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Dysprosium',
    abbreviation: 'Dy',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 66,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Holmium',
    abbreviation: 'Ho',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 67,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Erbium',
    abbreviation: 'Er',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 68,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Thullum',
    abbreviation: 'Tm',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 69,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Ytterbium',
    abbreviation: 'Yb',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 70,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Lutetium',
    abbreviation: 'Lu',
    type: 'Lanthanide',
    state: '',
    atomicNumber: 71,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Actinium',
    abbreviation: 'Ac',
    type: 'Actinide',
    state: '',
    atomicNumber: 89,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Thorium',
    abbreviation: 'Th',
    type: 'Actinide',
    state: '',
    atomicNumber: 90,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Protactinium',
    abbreviation: 'Pa',
    type: '',
    state: '',
    atomicNumber: 91,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Uranium',
    abbreviation: 'U',
    type: 'Actinide',
    state: '',
    atomicNumber: 92,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Neptunium',
    abbreviation: 'Np',
    type: 'Actinide',
    state: '',
    atomicNumber: 93,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Plutonium',
    abbreviation: 'Pu',
    type: 'Actinide',
    state: '',
    atomicNumber: 94,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Americium',
    abbreviation: 'Am',
    type: 'Actinide',
    state: '',
    atomicNumber: 95,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Curium',
    abbreviation: 'Cm',
    type: 'Actinide',
    state: '',
    atomicNumber: 96,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Berkelium',
    abbreviation: 'Bk',
    type: 'Actinide',
    state: '',
    atomicNumber: 97,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Californium',
    abbreviation: 'Cf',
    type: 'Actinide',
    state: '',
    atomicNumber: 98,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Einsteinium',
    abbreviation: 'Es',
    type: 'Actinide',
    state: '',
    atomicNumber: 99,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Fermium',
    abbreviation: 'Fm',
    type: 'Actinide',
    state: '',
    atomicNumber: 100,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Mendelevium',
    abbreviation: 'Md',
    type: 'Actinide',
    state: '',
    atomicNumber: 101,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Nobelium',
    abbreviation: 'No',
    type: 'Actinide',
    state: '',
    atomicNumber: 102,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
  {
    element: 'Lawrencium',
    abbreviation: 'Lr',
    type: 'Actinide',
    state: '',
    atomicNumber: 103,
    atomicWeight: undefined,
    protons: undefined,
    neutrons: undefined,
    electrons: undefined
  },
]

const elements = document.getElementById('elements');
console.log(elements);
function renderElements () {
	elements.innerHTML = '';

	elementsArray.forEach((element) => {
  	const listElement = document.createElement('li');

    const text = document.createElement('span');
    text.textContent = element.abbreviation;
    text.className = 'element';
    listElement.appendChild(text);

    elements.appendChild(listElement);
  });
}

renderElements();